
version: '3.1'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 8012:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ${SYMFONY_APP}:/home/wwwroot/sf4
        depends_on:
#          - engine-mao-prm
          - php

    percona-mao-certif:
        image: percona:5.7
#        image: mariadb
        ports:
        - "3310:3306"
        #    container_name: percona-mao
        container_name: percona-mao-certif
        environment:
        - "MYSQL_ROOT_PASSWORD=dev"
        - "MYSQL_DATABASE=mao_database"
        - "MYSQL_USER=admin"
        - "MYSQL_PASSWORD=admin"
        networks:
        - default

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - ${SYMFONY_APP}:/home/wwwroot/sf4
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - percona-mao-certif

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        restart: always
        ports:
            - 8080:80
        links:
            - percona-mao-certif
        environment:
          PMA_HOST: mysql

networks:
    default:
        external:
            name: sf4-api-platform-mirror

